import "./globals.css";
import type { Metadata } from "next";
import { Assistant, Poppins } from "next/font/google";
import "@/assets/styles/common.css";
import "@/assets/styles/components.css";
import "@/assets/styles/designPage.css";
import "@/assets/styles/homepage.css";
import "@/assets/styles/aboutUsPage.css";
import "@/assets/styles/productPage.css";
import "@/assets/styles/newsPage.css";
import "@/assets/styles/admin/auth.css";
import "@/assets/styles/admin/dashboard.css";
import "@/assets/styles/admin/table.css";
import "@/assets/styles/admin/dialog.css";
import "@/assets/styles/admin/blog.css";
import "draft-js/dist/Draft.css";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";

const assistant = Assistant({
  subsets: ["latin"],
  variable: "--font-assistant",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={assistant.className}>{children}</body>
    </html>
  );
}
