import Header from "@/components/Common/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Assistant, Inter } from "next/font/google";
import Footer from "@/components/Common/Footer";
import "@/assets/styles/common.css";
import "@/assets/styles/components.css";
import "@/assets/styles/designPage.css";
import "@/assets/styles/homepage.css";
import "@/assets/styles/aboutUsPage.css";

const assistant = Assistant({
  subsets: ["latin"],
  variable: "--font-assistant",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={assistant.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
