import "../globals.css";
import type { Metadata } from "next";
import Header from "@/components/Header/Header";
import PhoneHeader from "@/components/Header/PhoneHeader";
import Footer from "@/components/Common/Footer";
import LiveChatIcon from "@/components/Common/LiveChatIcon";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {
          <div>
            <div className="hidden xl:block">
              <Header />
            </div>

            <div className="block xl:hidden">
              <PhoneHeader />
            </div>
            {children}
            <LiveChatIcon />
            <Footer />
          </div>
        }
      </body>
    </html>
  );
}
