import "../globals.css";
import type { Metadata } from "next";
import { Assistant, Jost } from "next/font/google";
import "@/assets/styles/common.css";
import "@/assets/styles/components.css";
import "@/assets/styles/designPage.css";
import "@/assets/styles/homepage.css";
import "@/assets/styles/aboutUsPage.css";
import "@/assets/styles/productPage.css";
import "@/assets/styles/admin/auth.css";
import "@/assets/styles/admin/dashboard.css";
import "@/assets/styles/admin/table.css";
import "@/assets/styles/admin/dialog.css";
import "@/assets/styles/admin/blog.css";
import "@/pages/News/blog.css";
import "react-toastify/dist/ReactToastify.css";
import Header from "@/components/Common/Header";
import PhoneHeader from "@/components/Common/PhoneHeader";
import Footer from "@/components/Common/Footer";

const assistant = Assistant({
  subsets: ["latin"],
  variable: "--font-assistant",
});
export const jost = Jost({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={jost.className}>
        {
          <div>
            <div className="hidden xl:block">
              <Header />
            </div>

            <div className="block xl:hidden">
              <PhoneHeader />
            </div>
            {children}
            <Footer />
          </div>
        }
      </body>
    </html>
  );
}
